### ISSUE TITLE
not loging in stuck at 49 %

### ISSUE THREAD

**Issue by Saladin1812** [Erlandys/UE4LinuxLauncher#12]
not able to login 
![Screenshot from 2019-04-04 20-56-39](https://user-images.githubusercontent.com/40650341/55567857-3025df80-571c-11e9-9000-1c0b5aba77c4.png)

**Comment by diogobaeder** [comment]
Try enabling one of the available Two-Factor Authentication methods in your Epic account page. This worked for me, seems like this library has issues communicating with the server without 2fa.

**Comment by Erlandys** [comment]
Fixed login without Two-Facto Authentication method.
