### ISSUE TITLE
Doesn't show projects

### ISSUE THREAD

**Issue by Liemaeu** [Erlandys/UE4LinuxLauncher#15]
Suddendly it stopped to work. The Unreal Engine 4 (4.22.1) installation path is still correctly, the projects are still at the same place (and the Unreal Engine recognize them) but this UE4LinuxLauncher doesn't show it:
 
![Screenshot](https://user-images.githubusercontent.com/30625460/57986160-99b24100-7a71-11e9-9ee5-d9f7ccb80b06.png)

**Comment by Erlandys** [comment]
Fixed in newest update.
