### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by snakehaihai** [Erlandys/UE4LinuxLauncher#20]
Can not login using default usename password and without 2 Factor Auth. the error is 1008

with 2 Factor Auth, doesn't work either 

 it shows java.lang.NullPointerException in background terimnal

**Comment by bjoern-braun** [comment]
I have the same problem

**Comment by verres1** [comment]
Me also error code 1008.

**Comment by Saladin1812** [comment]
I dont think this is getting maintained any more :(

**Comment by neutrino-steak** [comment]
It seems like the creator isn't available to work on this right now, so I figured I would start playing around with the source code to see if I could find a solution.
It took me a while to figure out what was going wrong but I was eventually able to fix the 2FA and non-2FA login methods. I still have some work to do before it's functional, as none of the marketplace items will appear. But I should be able to fix that in the next day or two. 

![proof](https://user-images.githubusercontent.com/15641824/67162872-902d4d80-f31d-11e9-89bc-c7f49b198fb0.png)

**Comment by Saladin1812** [comment]
Great🙂 you can fork the repo and update it accordingly @neutrino-steak

**Comment by neutrino-steak** [comment]
I was a bit busier than expected this week, but I wanted to give an update on my progress.

I downloaded the launcher on my old windows laptop to examine the authorization process for the native windows launcher. There's quite a bit of difference in the authorization process for the Windows launcher compared to this one. After fixing some of the more straightforward bugs, I got some good insight from the Windows launcher in terms of how to best approach the remaining issues.

I've fixed a lot so far, but it's not functional enough for me to feel good about releasing it yet. Here's a list of what I've completed and what still needs more work.

```
[✓] = Fixed     [*] = in progress     [?] = Not working/unverified

- [✓] #1008 Login Error
- [✓] Incorrect URLs for certain API functions
- [✓] updateCategories() function response not recieving/parsing categories
- [✓] Items not displaying in marketplace
- [*] Owned Asset not collected; Authentication issue
- [?] Download assets from launcher
```
I'm gonna continue working through this in my spare time. I can't guarantee any specific time-frame for completion, although I'm hoping to get it done by this weekend or the middle of next week. There isn't much documentation out there for the changes in Unreal Engine's back-end configuration, so it's mostly trial and error at this point.

**Comment by neutrino-steak** [comment]
The launcher in my [fork repository](https://github.com/neutrino-steak/UE4LinuxLauncher) should be fully functional now.

If anyone experiences any bugs, you can create an issue on that repository and I'll work on fixing them. I'm somewhat expecting problems to arise with countries outside the US or languages other than English. I haven't tested under those parameters yet, so I'm not sure if it will break any of the URLs.

I hope this helps!

**Comment by Saladin1812** [comment]
Thats great.. Awesome work @neutrino-steak

**Comment by snakehaihai** [comment]
nice nice. good work
