### ISSUE TITLE
Credential error

### ISSUE THREAD

**Issue by Saladin1812** [Erlandys/UE4LinuxLauncher#4]
Operating system - Debian 9.5
When i try to login to epic games from web browser its fine but launcher at 20 percent says that credentials are invalid.
I have these dependencies installed to be safer.. 
nodejs npm openjdk8 
Also tried that on my RHEL 7.5 machine.

**Comment by Erlandys** [comment]
You use the newest version which I've uploaded today? Try to repeat the login process couple times if you can.

**Comment by Saladin1812** [comment]
Yes i downloaded the version updated 12 hours ago.

**Comment by Saladin1812** [comment]
![screenshot from 2018-09-17 04-06-58](https://user-images.githubusercontent.com/40650341/45601729-329a4380-ba2f-11e8-8d9e-081dcee77084.png)

**Comment by Erlandys** [comment]
I have updated the system. So try to use your email instead of your login and if it still won't work, launch shell script with **-d** argument and try to analyse cookies and inputs.

**Comment by Saladin1812** [comment]
Its working now using the email address, not in the previous Launcher tho but this update 18 hours ago .. thanks Erlandys for the support :)

**Comment by Erlandys** [comment]
Good then :)
