### ISSUE TITLE
Error #1008 on Login

### ISSUE THREAD

**Issue by jackfrye** [Erlandys/UE4LinuxLauncher#8]
![faillogin](https://user-images.githubusercontent.com/16147177/50497253-e5514900-0a03-11e9-90e9-12623dce01ff.png)

When I try to log in I am seeing this. There is no info in the terminal. I log in using my email address and password as on the web login. If I use my username and password, it gives me invalid credentials.

**Comment by lightway82** [comment]
+1

**Comment by LinuxDonald** [comment]
For me it works without problems. Im using Two-way-Auth. Ubuntu 18.04

**Comment by LinuxDonald** [comment]
linuxdonald@linuxdonald-desktop:~$ java -version
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

https://launchpad.net/~webupd8team/+archive/ubuntu/java

Maybe that helps for Ubuntu users?

**Comment by FuyuriSeiichi** [comment]
yes, it happen to me as well.

**Comment by loffermann** [comment]
Had the issue described here (with Ubuntu 18.04 and Java 8). I did resolve it by enabling two-factor authentication for my Epic Games account (using the E-Mail variant).

**Comment by infinityplusb** [comment]
@loffermann yes setting my account to use 2-Factor Auth solved it for me too. I used the App, not the email variant and it works fine.

**Comment by RicardoEPRodrigues** [comment]
The code either should make the error more explicit or be changed to allow not 2-Factor Auth accounts to log in.

**Comment by thebarz** [comment]
> Had the issue described here (with Ubuntu 18.04 and Java 8). I did resolve it by enabling two-factor authentication for my Epic Games account (using the E-Mail variant).

This worked for me, Thanks. (I didn't know that the extra verification existed)

**Comment by Erlandys** [comment]
Fixed login without Two-Facto Authentication method.

**Comment by mgh-ding** [comment]
> Fixed login without Two-Facto Authentication method.

Still got 1008 (CentOS 7)

- without 2 Factor Auth, it gives 1008

- with 2 Factor Auth, doesn't work either (after typing in the 6-digit code and clicking "Confirm", the program got stuck there). In terminal, it shows `java.lang.NullPointerException`
